### ISSUE TITLE
Output from TestHubspace.py

### ISSUE THREAD

**Issue by xmetisx** [jdeath/Hubspace-Homeassistant#35]
[TestHubspace Output.txt](https://github.com/jdeath/Hubspace-Homeassistant/files/11242979/TestHubspace.Output.txt)

new model Driskol 60inch ceiling fan/light.  Both entities detected, fan turns on and off only.  Light does nothing.

**Comment by jdeath** [comment]
Yes, this fan works differently than others. Also, it does not return a model name, which will make it tricky to code. It may take me a few days/week to get to this updated. In the meantime, you can use services to send commands. Other commands you can figure out from test output following the examples below. But these should get your started.

Turn light on:
```
service: hubspace.send_command
data:
  value: "on"
  functionClass: power
  functionInstance: light-power
target:
  entity_id: light.cieling_light  
```
Replace off with on to turn it off. 
For Brightness (change value to 0 - 100):
```
service: hubspace.send_command
data:
  value: 100
  functionClass: brightness
target:
  entity_id: light.cieling_light  
```

For fan speed (change the 100 to 020, 040, 060, 080
```
service: hubspace.send_command
data:
  value: fan-speed-5-100
  functionClass: fan-speed
  functionInstance: fan-speed
target:
  entity_id: light.cieling_fan 
```
