### ISSUE TITLE
Request: Improved support for 60" DriskolFan

### ISSUE THREAD

**Issue by avoroshilov** [jdeath/Hubspace-Homeassistant#51]
Hello! We bought a 60" Hampton Bay fan, which turned out to be DriskolFan as it seems. In FCC, it is filed as RGB-60SNYDS.
I am not sure if I am doing everything correctly with this integration, but I've set it using the fan template provided, and I think it largely works with percentages and whatnot, but it doesn't have any improved controls, such as:
- fan-reverse
- comfort/natural breeze
- color temperature selection

I see people here are providing the debug data requesting support, so I figured I'll give this a shot. So, my fan is integrated as two separate entities and here are relevant excerpts (with WiFi and other data removed) for both entities:
* `light.ceiling_fan_2` (fan entity):
```
supported_color_modes: brightness
model: DriskolFan
deviceId: 85be083a8d38d822
values:
  - functionClass: fan-reverse
    functionInstance: fan-reverse
    value: forward
  - functionClass: power
    functionInstance: fan-power
    value: 'on'
  - functionClass: toggle
    functionInstance: comfort-breeze
    value: disabled
  - functionClass: fan-speed
    functionInstance: fan-speed
    value: fan-speed-5-020
  - functionClass: timer
    functionInstance: fan-power
    value: 0
```
it also has a bunch of other entities that can theoretically be exposed just for the sake of statistics maybe? (like `wifi-ssid`, `wifi-rssi` - could be quite useful for gauging the connection! as well as `wifi-steady-state` / `wifi-setup-state`)

* `light.ceiling_light` (this entity controls the light of said fan):
```
min_color_temp_kelvin: 2695
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 371
supported_color_modes: brightness, color_temp, white
model: 
deviceId: 85be083a8d38d822
values:
  - functionClass: brightness
    value: 100
  - functionClass: power
    functionInstance: light-power
    value: 'off'
  - functionClass: color-temperature
    value: 2700K

supported_features: 0
```
and it also has same WiFi parameters duplicated.

It would be great to understand how this data can be used - is there any way to extract it as entity attributes, so that I can build a template with the color temperature? Or code modification is needed to support this model?

Judging by the data available, this fan can be made fully functional in HA thanks to this integration!
