### ISSUE TITLE
README Suggestion: Set RGB Color

### ISSUE THREAD

**Issue by Adanufgail** [jdeath/Hubspace-Homeassistant#73]
Hello! I spent some time this morning trying to get buttons set up to change a light to a custom color. I wrote up an example for setting a light to a manual color (purple in this instance) and one for setting brightness for the README.

It should also maybe be noted that only one state can be changed at a time and if you want to change color and brightness, you need to script it to make two hubspace.send_command calls.

Change RGB Color:
```
type: button
entity: light.lightname
name: Set Light Purple
show_name: true
show_icon: true
tap_action:
  action: call-service
  service: hubspace.send_command
  data:
    value: {"color-rgb": {"r": 215,"g": 150,"b": 255}}
    functionClass: color-rgb
  target:
    entity_id: light.lightname
```

Change Brightness, value is an integer percentage from 1 to 100:
```
type: button
entity: light.lightname
name: Set Brightness 50%
show_name: true
show_icon: true
tap_action:
  action: call-service
  service: hubspace.send_command
  data:
    value: 50
    functionClass: brightness
  target:
    entity_id: light.lightname
```
